### ISSUE TITLE
Lockfiles should be included

### ISSUE THREAD

**Issue by devmattrick** [ljharb/object-keys#49]
In reference to commit 4f96621e53cabd0649ebaaf851d3f4328fcd26ff, all projects should have lockfiles. This is generally a best practice accepted among both the NPM and Yarn community.

See:
- https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/
- https://docs.npmjs.com/files/package-lock.json
- https://stackoverflow.com/a/44904494

**Comment by devmattrick** [comment]
I would implore you to rethink your stance on this. [Many](https://github.com/facebook/react/blob/master/yarn.lock) [large](https://github.com/webpack/webpack/blob/master/yarn.lock) [libraries](https://github.com/vuejs/vue/blob/dev/yarn.lock) include lockfiles for the reasons listed in the links I've provided.

At the end of the day, this is your project and you are free to manage it how you choose, but I would argue that it provides relatively many advantages with relatively few disadvantages.

**Comment by ljharb** [comment]
I find many disadvantages and zero advantages ¯\_(ツ)_/¯ as such, all 100+ of my projects will never have lockfiles as long as I’m alive to maintain them.

**Comment by ljharb** [comment]
Either way, I’m very confused why you care - package-lock and yarn.lock are dev-only lockfiles. Literally the only humans who ever will be impacted by their presence are the actual maintainers of the library. Since I’m the sole maintainer of this package, I’m the only one who could be affected - whether positively or negatively.
